In [ ]:
#3번
import numpy as np
from scipy import linalg
def g(x):
  n=len(x)
  q2=[]
  norm = linalg.norm(x[0])
  x[0] = x[0]/norm
  q2.append(x[0])
  for i in range(1,n):
    q2.append(x[i])
  for i in range(1,n):
    for j in range(0,i):
      q2[i] = q2[i] - q2[i].dot(q2[j])*q2[j]
    norm = linalg.norm(q2[i])
    q2[i] = -q2[i]/norm
  q2[0] = -q2[0]
  q2=np.array(q2)
  q2=q2.transpose()
  return q2

In [ ]:
a=np.array([[1.0,2.0,3.0],[-1.0,3.0,2.0],[2.0,1.0,-2.0]])
b=a.transpose()
Q = g(b)

In [ ]:
Q

array([[-0.40824829, -0.49292179, -0.76834982],
       [ 0.40824829, -0.85141036,  0.32929278],
       [-0.81649658, -0.17924429,  0.5488213 ]])

In [ ]:
A=[[1,2,3],[-1,3,2],[2,1,-2]]
np.dot(Q.transpose(),A)

array([[-2.44948974e+00, -4.08248290e-01,  1.22474487e+00],
       [ 1.66533454e-16, -3.71931893e+00, -2.82309750e+00],
       [-4.44089210e-16,  2.22044605e-16, -2.74410650e+00]])

In [ ]:
linalg.qr(A)

(array([[-0.40824829, -0.49292179, -0.76834982],
        [ 0.40824829, -0.85141036,  0.32929278],
        [-0.81649658, -0.17924429,  0.5488213 ]]),
 array([[-2.44948974, -0.40824829,  1.22474487],
        [ 0.        , -3.71931893, -2.8230975 ],
        [ 0.        ,  0.        , -2.7441065 ]]))